### ISSUE TITLE
Not able to see code on published site.

### ISSUE THREAD

**Issue by divsoft** [Weebly/code-block-app#7]
Browser used : Chrome, Firefox 
Post URL : http://diveshblog.weebly.com/blog/angular-2-a-guide-for-beginners-by-a-beginner

I downloaded the code editor from app center and used the component, I am able to see code in edit mode and then I published the post.
![image](https://cloud.githubusercontent.com/assets/8091773/18710391/a7ebd156-8022-11e6-8fd1-a55af3738937.png)

But it is not reflecting on the published site , I have cleared cache , checked on another browser as well but it is rendered as a line only . In case we turn off the header, else only header is visible.

![image](https://cloud.githubusercontent.com/assets/8091773/18710537/64e82d4a-8023-11e6-86a5-e7c71e683391.png)

**Comment by tjsnyder** [comment]
Hi,
I was unable to reproduce the issue. The current blog post only has one line to display as well.

If you come across this issue in the future, can you link me to the broken published site?
